package org.jboss.qa.examples.bpm_taxi;

import org.jboss.qa.examples.bpm_taxi.Customer
import org.jboss.qa.examples.bpm_taxi.Drive

/*
  TODO: sets constant price, must compute it based on distance and customer's history
*/
rule 'calculatePrice'
ruleflow-group 'calculatePrice'
no-loop
when
  drive : Drive()
then
  System.out.println("********** rule task 'calculatePrice' **********");
  drive.setPrice(500.0);
  update(drive);
  System.out.println("Drive: " + drive);
end
