package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Address extends Entity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private String line;
    private Location location;

    public Address() {
    }

    public Address(final String line) {
        this.line = line;
    }

    public Address(java.lang.String line, Location location) {
        this.line = line;
        this.location = location;
    }

    public java.lang.String getLine() {
        return this.line;
    }

    public void setLine(java.lang.String line) {
        this.line = line;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(final Location location) {
        this.location = location;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Address)) return false;

        Address address = (Address) o;

        return !(line != null ? !line.equals(address.line) : address.line != null);

    }
    
     public String toString() {
        return line + " :: " + (location == null? "null" : location );
    }

    @Override
    public int hashCode() {
        return line != null ? line.hashCode() : 0;
    }
}