package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Address extends Entity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String city;
    private java.lang.String street;
    private Location location;

    public Address() {
    }

    public Address(final String city, final String street) {
        this.city = city;
        this.street = street;
    }

    public Address(java.lang.String city, java.lang.String street, Location location) {
        this.city = city;
        this.street = street;
        this.location = location;
    }

    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getStreet() {
        return this.street;
    }

    public void setStreet(java.lang.String street) {
        this.street = street;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(final Location location) {
        this.location = location;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Address)) return false;

        Address address = (Address) o;

        if (city != null ? !city.equals(address.city) : address.city != null) return false;
        return !(street != null ? !street.equals(address.street) : address.street != null);

    }

    @Override
    public int hashCode() {
        int result = city != null ? city.hashCode() : 0;
        result = 31 * result + (street != null ? street.hashCode() : 0);
        return result;
    }
}