package org.jboss.qa.examples.bpm_taxi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String city;
   private java.lang.String street;

   public Address()
   {
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public Address(java.lang.String city, java.lang.String street)
   {
      this.city = city;
      this.street = street;
   }

}