package org.jboss.qa.examples.bpm_taxi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String surname;

   private java.util.List<org.jboss.qa.examples.bpm_taxi.Drive> history;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public java.util.List<org.jboss.qa.examples.bpm_taxi.Drive> getHistory()
   {
      return this.history;
   }

   public void setHistory(
         java.util.List<org.jboss.qa.examples.bpm_taxi.Drive> history)
   {
      this.history = history;
   }

   public Customer(java.lang.String name, java.lang.String surname,
         java.util.List<org.jboss.qa.examples.bpm_taxi.Drive> history)
   {
      this.name = name;
      this.surname = surname;
      this.history = history;
   }

}