package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.xml.bind.annotation.XmlRootElement(name = "drive")
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(propOrder = { "from", "to", "price",
      "refused", "taxi" })
public class Drive implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Address from;
   private Address to;
   private java.lang.Double price;

   private org.jboss.qa.examples.bpm_taxi.Taxi taxi;

   private boolean refused;

   private java.util.Date arrivalTime;

   public Drive()
   {
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public org.jboss.qa.examples.bpm_taxi.Taxi getTaxi()
   {
      return this.taxi;
   }

   public void setTaxi(org.jboss.qa.examples.bpm_taxi.Taxi taxi)
   {
      this.taxi = taxi;
   }

   public org.jboss.qa.examples.bpm_taxi.Address getFrom()
   {
      return this.from;
   }

   public void setFrom(org.jboss.qa.examples.bpm_taxi.Address from)
   {
      this.from = from;
   }

   public org.jboss.qa.examples.bpm_taxi.Address getTo()
   {
      return this.to;
   }

   public void setTo(org.jboss.qa.examples.bpm_taxi.Address to)
   {
      this.to = to;
   }

   public boolean isRefused()
   {
      return this.refused;
   }

   public void setRefused(boolean refused)
   {
      this.refused = refused;
   }

   public java.util.Date getArrivalTime()
   {
      return this.arrivalTime;
   }

   public void setArrivalTime(java.util.Date arrivalTime)
   {
      this.arrivalTime = arrivalTime;
   }

   public Drive(org.jboss.qa.examples.bpm_taxi.Address from,
         org.jboss.qa.examples.bpm_taxi.Address to, java.lang.Double price,
         org.jboss.qa.examples.bpm_taxi.Taxi taxi, boolean refused,
         java.util.Date arrivalTime)
   {
      this.from = from;
      this.to = to;
      this.price = price;
      this.taxi = taxi;
      this.refused = refused;
      this.arrivalTime = arrivalTime;
   }
}