package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement(name = "drive")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
        "from",
        "to",
        "price",
        "refused",
        "taxi"
})
public class Drive implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Address from;
    private Address to;
    private java.lang.Double price;

    private org.jboss.qa.examples.bpm_taxi.Taxi taxi;

    private boolean refused;

    public Drive() {
    }

    public java.lang.Double getPrice() {
        return this.price;
    }

    public void setPrice(java.lang.Double price) {
        this.price = price;
    }

    public org.jboss.qa.examples.bpm_taxi.Taxi getTaxi() {
        return this.taxi;
    }

    public void setTaxi(org.jboss.qa.examples.bpm_taxi.Taxi taxi) {
        this.taxi = taxi;
    }

    public org.jboss.qa.examples.bpm_taxi.Address getFrom() {
        return this.from;
    }

    public void setFrom(org.jboss.qa.examples.bpm_taxi.Address from) {
        this.from = from;
    }

    public org.jboss.qa.examples.bpm_taxi.Address getTo() {
        return this.to;
    }

    public void setTo(org.jboss.qa.examples.bpm_taxi.Address to) {
        this.to = to;
    }

    public boolean isRefused() {
        return this.refused;
    }

    public void setRefused(boolean refused) {
        this.refused = refused;
    }

    public Drive(org.jboss.qa.examples.bpm_taxi.Address from,
                 org.jboss.qa.examples.bpm_taxi.Address to, java.lang.Double price,
                 org.jboss.qa.examples.bpm_taxi.Taxi taxi, boolean refused) {
        this.from = from;
        this.to = to;
        this.price = price;
        this.taxi = taxi;
        this.refused = refused;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Drive)) return false;

        Drive drive = (Drive) o;

        if (!from.equals(drive.from)) return false;
        if (!to.equals(drive.to)) return false;
        return taxi.equals(drive.taxi);

    }

    @Override
    public int hashCode() {
        int result = from.hashCode();
        result = 31 * result + to.hashCode();
        result = 31 * result + taxi.hashCode();
        return result;
    }
}