package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement(name = "drive")
@XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@XmlType(propOrder = {
        "from",
        "to",
        "price",
        "refused",
        "arrivalTime",
        "taxi"
})
public class Drive implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @XmlIDREF
    private Address from;
    @XmlIDREF
    private Address to;
    private java.lang.Double price;
    @XmlIDREF
    private org.jboss.qa.examples.bpm_taxi.Taxi taxi;

    private boolean refused;

    private java.util.Date arrivalTime;

    public Drive() {
    }

    public java.lang.Double getPrice() {
        return this.price;
    }

    public void setPrice(java.lang.Double price) {
        this.price = price;
    }

    public org.jboss.qa.examples.bpm_taxi.Taxi getTaxi() {
        return this.taxi;
    }

    public void setTaxi(org.jboss.qa.examples.bpm_taxi.Taxi taxi) {
        this.taxi = taxi;
    }

    public org.jboss.qa.examples.bpm_taxi.Address getFrom() {
        return this.from;
    }

    public void setFrom(org.jboss.qa.examples.bpm_taxi.Address from) {
        this.from = from;
    }

    public org.jboss.qa.examples.bpm_taxi.Address getTo() {
        return this.to;
    }

    public void setTo(org.jboss.qa.examples.bpm_taxi.Address to) {
        this.to = to;
    }

    public boolean isRefused() {
        return this.refused;
    }

    public boolean getRefused() {
        return this.refused;
    }

    public void setRefused(boolean refused) {
        this.refused = refused;
    }

    public java.util.Date getArrivalTime() {
        return this.arrivalTime;
    }

    public void setArrivalTime(java.util.Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    public Drive(org.jboss.qa.examples.bpm_taxi.Address from,
                 org.jboss.qa.examples.bpm_taxi.Address to, java.lang.Double price,
                 org.jboss.qa.examples.bpm_taxi.Taxi taxi, boolean refused,
                 java.util.Date arrivalTime) {
        this.from = from;
        this.to = to;
        this.price = price;
        this.taxi = taxi;
        this.refused = refused;
        this.arrivalTime = arrivalTime;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Drive)) return false;

        Drive drive = (Drive) o;

        if (refused != drive.refused) return false;
        if (from != null ? !from.equals(drive.from) : drive.from != null) return false;
        if (to != null ? !to.equals(drive.to) : drive.to != null) return false;
        if (price != null ? !price.equals(drive.price) : drive.price != null) return false;
        if (taxi != null ? !taxi.equals(drive.taxi) : drive.taxi != null) return false;
        return !(arrivalTime != null ? !arrivalTime.equals(drive.arrivalTime) : drive.arrivalTime != null);

    }

    @Override
    public int hashCode() {
        int result = from != null ? from.hashCode() : 0;
        result = 31 * result + (to != null ? to.hashCode() : 0);
        result = 31 * result + (price != null ? price.hashCode() : 0);
        result = 31 * result + (taxi != null ? taxi.hashCode() : 0);
        result = 31 * result + (refused ? 1 : 0);
        result = 31 * result + (arrivalTime != null ? arrivalTime.hashCode() : 0);
        return result;
    }
}