package org.jboss.qa.examples.bpm_taxi;

import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlIDREF;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class Taxi extends Entity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @XmlIDREF
    private Address currentLocation;

    public boolean isInUse() {
        return inUse;
    }

    public void setInUse(final boolean inUse) {
        this.inUse = inUse;
    }

    private boolean inUse = false;
    private java.lang.String car;

    public Taxi() {
    }

    public Taxi(org.jboss.qa.examples.bpm_taxi.Address currentLocation, java.lang.String car, boolean inUse) {
        this.currentLocation = currentLocation;
        this.car = car;
        this.inUse = inUse;
    }

    public org.jboss.qa.examples.bpm_taxi.Address getCurrentLocation() {
        return this.currentLocation;
    }

    public void setCurrentLocation(
            org.jboss.qa.examples.bpm_taxi.Address currentLocation) {
        this.currentLocation = currentLocation;
    }

    public java.lang.String getCar() {
        return this.car;
    }

    public void setCar(java.lang.String car) {
        this.car = car;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Taxi)) return false;

        Taxi taxi = (Taxi) o;

        return car.equals(taxi.car);
    }

    @Override
    public int hashCode() {
        return car.hashCode();
    }
}