package org.jboss.qa.examples.bpm_taxi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Taxi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Address currentLocation;

   private java.lang.String car;

   public Taxi()
   {
   }

   public org.jboss.qa.examples.bpm_taxi.Address getCurrentLocation()
   {
      return this.currentLocation;
   }

   public void setCurrentLocation(
         org.jboss.qa.examples.bpm_taxi.Address currentLocation)
   {
      this.currentLocation = currentLocation;
   }

   public java.lang.String getCar()
   {
      return this.car;
   }

   public void setCar(java.lang.String car)
   {
      this.car = car;
   }

   public Taxi(org.jboss.qa.examples.bpm_taxi.Address currentLocation,
         java.lang.String car)
   {
      this.currentLocation = currentLocation;
      this.car = car;
   }

   @Override
   public boolean equals(final Object o) {
      if (this == o) return true;
      if (!(o instanceof Taxi)) return false;

      Taxi taxi = (Taxi) o;

      return car.equals(taxi.car);

   }

   @Override
   public int hashCode() {
      return car.hashCode();
   }
}